#
#If you have any questions, problems, or suggestions please add me on Discord (Scarmo#6191) and send me a message.
#Configuration begins below.
#

#Here you can specify in which worlds the teleport bow should not work.
blacklisted-worlds:
  - "blacklistedworld1"
  - "blacklistedworld2"

#If the player shoots multiple arrows before any of them has landed, you can choose if they get teleported to
#all of them one after one, or if they only get teleported to the latest arrow they have shot.
#LATEST = Only teleport to the latest arrow shot.
#ALL = Teleport to all the arrows shot, one after one.
teleport-to: LATEST

#Different options for sound
teleport-sound:
  #Do you a sound to play when a player gets teleported to the arrow location? true/false
  enabled: false
  #What type of particle should be used? NOTE: This is different for every version. You will have to find the sound name yourself.
  sound: ENTITY_ENDERMAN_TELEPORT

#Different options for particles
teleport-particle:
  #Do you want particles to spawn when a player gets teleported to the arrow location? true/false
  enabled: true
  #What type of particle should be used? NOTE: This is different for every version. You will have to find the particle name yourself.
  particle: SPELL_WITCH

#Options for the Teleport Bow item
bow:
  on-join:
    #Do you want to give players a Teleport Bow when they connect to the server? true/false
    give: true
    #In what slot should the Teleport Bow be given? NOTE: Slots start from 0. Slot 1 in the inventory = Slot 0 in the config.
    inventory-slot: 0
    #Do you want to deny players from dropping the bow?
    #Bypass permission: tbp.dropbow
    deny-drop: true
    #Do you want to deny players from moving the bow around in their inventory?
    #Bypass permission: tbp.movebow
    deny-move: true
  #What should the name of the Teleport Bow item be? Set to "" for no name.
  display-name: "&dTeleport Bow"
  #What should the lore of the Teleport Bow item be? Set to [] for no lore.
  lore:
    - ""
    - "&7Shoot an arrow with this bow and get"
    - "&7teleported to where it lands!"
    - ""
  #Should the Teleport Bow have an enchanted glow to it? true/false
  glowing: true
  #Should the bow have the "Infinity" enchantment applied? true/false
  infinity: true
  #Should the bow never lose durability?
  unbreakable: true

#Options for the arrow item
arrow:
  on-join:
    #Do you want to give players an arrow for the Teleport Bow when they connect to the server? true/false
    give: true
    #In what slot should the arrow be given? NOTE: Slots start from 0. Slot 1 in the inventory = Slot 0 in the config.
    inventory-slot: 9
    #How many arrows would you like to give?
    amount: 1
    #Do you want to deny players from dropping the arrow/arrows?
    #Bypass permission: tbp.droparrow
    deny-drop: true
    #Do you want to deny players from moving the bow around in their inventory?
    #Bypass permission: tbp.movebow
    deny-move: true
  #What should the name of the arrow item be? Set to "" for no name.
  display-name: "&dArrow"
  #What should the lore of the arrow item be? Set to [] for no lore.
  lore:
    - ""
    - "&7An arrow used for the Teleport Bow."
    - ""
  #Should the arrow have an enchanted glow to it? true/false
  glowing: false
  #Should arrows shot from Teleport Bows despawn when hitting the ground?
  despawn: true
  particle-trail:
    #Do you want to send a trail of particles after arrows shot from a Teleport Bow?
    enabled: true
    #What type of particle should be used?
    particle: SPELL_WITCH
    #How often should particles be displayed? In ticks. (20 ticks = 1 second)
    interval: 1